In [ ]:
import pandas as pd
from prepare_dataset import load_clean_dataframe

In [ ]:
df = load_clean_dataframe()
df[["date_parsed_et", "text_clean"]].head()

       date_parsed_et                                         text_clean
0 2026-04-09 08:40:00  None of these people, including our own, very ...
1 2026-04-08 23:46:00  All U.S. Ships, Aircraft, and Military Personn...
2 2026-04-08 22:56:00  The Failing New York Times and Fake News CNN e...
3 2026-04-08 19:31:00  NATO WASN’T THERE WHEN WE NEEDED THEM, AND THE...
4 2026-04-08 12:20:00  Marjorie “Traitor” Brown’s (GREEN TURNS TO BRO...

In [ ]:
raw_df = pd.read_csv("factbase_truthsocial_texts.csv")
clean_df = pd.read_csv("factbase_truthsocial_texts_clean.csv")

print("raw shape:", raw_df.shape)
print("clean shape:", clean_df.shape)

raw shape: (9788, 4)
clean shape: (9788, 10)

In [4]:
print(raw_df.columns)
print(clean_df.columns)

Index(['date_et', 'truth_social_url', 'text', 'raw_card_text'], dtype='str')
Index(['post_id', 'date_parsed_et', 'date_et', 'truth_social_url',
       'text_clean', 'text_length', 'word_count', 'is_duplicate_text', 'text',
       'raw_card_text'],
      dtype='str')

In [5]:
raw_df["text"].isna().sum(), clean_df["text_clean"].isna().sum()

(np.int64(0), np.int64(2341))

In [6]:
raw_empty = raw_df["text"].fillna("").str.strip().eq("").sum()
clean_empty = clean_df["text_clean"].fillna("").str.strip().eq("").sum()

print("raw empty texts:", raw_empty)
print("clean empty texts:", clean_empty)

raw empty texts: 0
clean empty texts: 2341

In [7]:
raw_df[["date_et", "truth_social_url", "text"]].head(10)

,date_et,truth_social_url,text
0,"April 9, 2026 @ 8:40 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nNone of ...
1,"April 8, 2026 @ 11:46 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nAll U.S....
2,"April 8, 2026 @ 10:56 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nThe Fail...
3,"April 8, 2026 @ 7:31 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nNATO WAS...
4,"April 8, 2026 @ 12:20 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nMarjorie...
5,"April 8, 2026 @ 12:04 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nNumerous...
6,"April 8, 2026 @ 10:51 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nSecretar...
7,"April 8, 2026 @ 7:30 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nA Countr...
8,"April 8, 2026 @ 7:22 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nThe Unit...
9,"April 8, 2026 @ 7:00 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •

In [10]:
compare = pd.DataFrame({
    "date_et": raw_df["date_et"],
    "url": raw_df["truth_social_url"],
    "raw_text": raw_df["text"],
    "clean_text": clean_df["text_clean"]
})

compare.head(10)

,date_et,url,raw_text,clean_text
0,"April 9, 2026 @ 8:40 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nNone of ...,"None of these people, including our own, very ..."
1,"April 8, 2026 @ 11:46 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nAll U.S....,"All U.S. Ships, Aircraft, and Military Personn..."
2,"April 8, 2026 @ 10:56 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nThe Fail...,The Failing New York Times and Fake News CNN e...
3,"April 8, 2026 @ 7:31 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nNATO WAS...,"NATO WASN’T THERE WHEN WE NEEDED THEM, AND THE..."
4,"April 8, 2026 @ 12:20 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nMarjorie...,Marjorie “Traitor” Brown’s (GREEN TURNS TO BRO...
5,"April 8, 2026 @ 12:04 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nNumerous...,"Numerous Agreements, Lists, and Letters are be..."
6,"April 8, 2026 @ 10:51 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nSecretar...,Secretary Hegseth and Chairman Caine hold a pr...
7,"April 8, 2026 @ 7:30 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nA Countr...,A Country supplying Military Weapons to Iran w...
8,"April 8, 2026 @ 7:22 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social • \r\nThe Unit...,"The United States will work closely with Iran,..."
9,"April 8, 2026 @ 7:00 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN

In [11]:
suspicious = compare[
    compare["raw_text"].fillna("").str.strip().ne("") &
    compare["clean_text"].fillna("").str.strip().eq("")
]

print("suspicious rows:", len(suspicious))
suspicious.head(20)

suspicious rows: 2341

,date_et,url,raw_text,clean_text
9,"April 8, 2026 @ 7:00 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
49,"April 6, 2026 @ 11:45 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
50,"April 6, 2026 @ 11:42 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
54,"April 6, 2026 @ 8:15 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
55,"April 6, 2026 @ 8:14 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
63,"April 6, 2026 @ 7:07 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
67,"April 6, 2026 @ 12:29 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
69,"April 5, 2026 @ 10:35 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
71,"April 5, 2026 @ 5:49 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
73,"April 5, 2026 @ 5:46 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
81,"April 4, 2026 @ 4:26 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
82,"April 4, 2026 @ 3:56 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
83,"April 4, 2026 @ 3:56 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
84,"April 4, 2026 @ 3:56 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
93,"April 3, 2026 @ 7:10 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
101,"April 2, 2026 @ 6:29 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
102,"April 2, 2026 @ 6:29 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
106,"April 2, 2026 @ 12:15 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
118,"April 1, 2026 @ 6:35 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN
124,"March 31, 2026 @ 10:49 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •,NaN

In [12]:
len(raw_df), len(clean_df)

(9788, 9788)

In [13]:
suspicious[["date_et", "url", "raw_text"]].head(20)

,date_et,url,raw_text
9,"April 8, 2026 @ 7:00 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
49,"April 6, 2026 @ 11:45 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
50,"April 6, 2026 @ 11:42 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
54,"April 6, 2026 @ 8:15 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
55,"April 6, 2026 @ 8:14 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
63,"April 6, 2026 @ 7:07 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
67,"April 6, 2026 @ 12:29 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
69,"April 5, 2026 @ 10:35 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
71,"April 5, 2026 @ 5:49 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
73,"April 5, 2026 @ 5:46 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
81,"April 4, 2026 @ 4:26 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
82,"April 4, 2026 @ 3:56 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
83,"April 4, 2026 @ 3:56 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
84,"April 4, 2026 @ 3:56 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
93,"April 3, 2026 @ 7:10 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
101,"April 2, 2026 @ 6:29 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
102,"April 2, 2026 @ 6:29 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
106,"April 2, 2026 @ 12:15 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
118,"April 1, 2026 @ 6:35 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •
124,"March 31, 2026 @ 10:49 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,@realDonaldTrump • Truth Social •

In [15]:
suspicious["raw_text"].value_counts().head(10)

raw_text
@realDonaldTrump • Truth Social •    2341
Name: count, dtype: int64

In [16]:
raw_df.loc[suspicious.index[:20], ["date_et", "text", "raw_card_text"]]

,date_et,text,raw_card_text
9,"April 8, 2026 @ 7:00 AM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
49,"April 6, 2026 @ 11:45 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
50,"April 6, 2026 @ 11:42 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
54,"April 6, 2026 @ 8:15 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
55,"April 6, 2026 @ 8:14 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
63,"April 6, 2026 @ 7:07 AM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
67,"April 6, 2026 @ 12:29 AM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
69,"April 5, 2026 @ 10:35 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
71,"April 5, 2026 @ 5:49 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
73,"April 5, 2026 @ 5:46 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
81,"April 4, 2026 @ 4:26 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
82,"April 4, 2026 @ 3:56 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
83,"April 4, 2026 @ 3:56 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
84,"April 4, 2026 @ 3:56 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
93,"April 3, 2026 @ 7:10 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
101,"April 2, 2026 @ 6:29 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
102,"April 2, 2026 @ 6:29 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
106,"April 2, 2026 @ 12:15 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
118,"April 1, 2026 @ 6:35 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...
124,"March 31, 2026 @ 10:49 PM ET",@realDonaldTrump • Truth Social •,Donald Trump\r\n@realDonaldTrump • Truth Soci...

In [17]:
raw_df.loc[suspicious.index, "text"].str.replace("@realDonaldTrump • Truth Social •", "", regex=False).str.strip().head(20)

9
49
50
54
55
63
67
69
71
73
81
82
83
84
93
101
102
106
118
124
Name: text, dtype: str

In [18]:
print("raw rows:", len(raw_df))
print("clean rows:", len(clean_df))

raw rows: 9788
clean rows: 9788

In [19]:
clean_df = pd.read_csv("factbase_truthsocial_texts_clean.csv", keep_default_na=False)

In [20]:
clean_df["text_clean"].fillna("").str.strip().eq("").sum()

np.int64(2341)

In [21]:
model_df = clean_df[clean_df["text_clean"].str.strip() != ""].copy()
print(model_df.shape)

(7447, 10)

In [22]:
model_df.head(10)

,post_id,date_parsed_et,date_et,truth_social_url,text_clean,text_length,word_count,is_duplicate_text,text,raw_card_text
0,116374792489555954,2026-04-09 08:40:00,"April 9, 2026 @ 8:40 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,"None of these people, including our own, very ...",132,19,False,@realDonaldTrump • Truth Social • \r\nNone of ...,Donald Trump\r\n@realDonaldTrump • Truth Soci...
1,116372694697146221,2026-04-08 23:46:00,"April 8, 2026 @ 11:46 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,"All U.S. Ships, Aircraft, and Military Personn...",770,129,False,@realDonaldTrump • Truth Social • \r\nAll U.S....,Donald Trump\r\n@realDonaldTrump • Truth Soci...
2,116372497116210545,2026-04-08 22:56:00,"April 8, 2026 @ 10:56 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,The Failing New York Times and Fake News CNN e...,261,48,False,@realDonaldTrump • Truth Social • \r\nThe Fail...,Donald Trump\r\n@realDonaldTrump • Truth Soci...
3,116371693008302124,2026-04-08 19:31:00,"April 8, 2026 @ 7:31 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,"NATO WASN’T THERE WHEN WE NEEDED THEM, AND THE...",157,28,False,@realDonaldTrump • Truth Social • \r\nNATO WAS...,Donald Trump\r\n@realDonaldTrump • Truth Soci...
4,116369995519355709,2026-04-08 12:20:00,"April 8, 2026 @ 12:20 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,Marjorie “Traitor” Brown’s (GREEN TURNS TO BRO...,406,64,False,@realDonaldTrump • Truth Social • \r\nMarjorie...,Donald Trump\r\n@realDonaldTrump • Truth Soci...
5,116369934305888462,2026-04-08 12:04:00,"April 8, 2026 @ 12:04 PM ET",https://truthsocial.com/@realDonaldTrump/posts...,"Numerous Agreements, Lists, and Letters are be...",760,127,False,@realDonaldTrump • Truth Social • \r\nNumerous...,Donald Trump\r\n@realDonaldTrump • Truth Soci...
6,116369645448805093,2026-04-08 10:51:00,"April 8, 2026 @ 10:51 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,Secretary Hegseth and Chairman Caine hold a pr...,141,14,False,@realDonaldTrump • Truth Social • \r\nSecretar...,Donald Trump\r\n@realDonaldTrump • Truth Soci...
7,116368854361048135,2026-04-08 07:30:00,"April 8, 2026 @ 7:30 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,A Country supplying Military Weapons to Iran w...,218,35,False,@realDonaldTrump • Truth Social • \r\nA Countr...,Donald Trump\r\n@realDonaldTrump • Truth Soci...
8,116368825638596650,2026-04-08 07:22:00,"April 8, 2026 @ 7:22 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,"The United States will work closely with Iran,...",623,108,False,@realDonaldTrump • Truth Social • \r\nThe Unit...,Donald Trump\r\n@realDonaldTrump • Truth Soci...
10,116367088879643074,2026-04-08 00:01:00,"April 8, 2026 @ 12:01 AM ET",https://truthsocial.com/@realDonaldTrump/posts...,A big day for World Peace! Iran wants it to ha...,578,104,False,@realDonaldTrump • Truth Social • \r\nA big da...,Donald Trump\r\n@realDonaldTrump • Truth Soci...